apiVersion: apps/v1
kind: Deployment
metadata:
  name: anuja-app-deployment
spec: #define deployment
  replicas: 3 #number of pods
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels:
        app: web 
    spec: #define pod behaviour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
