apiVersion: apps/v1
kind: Deployment
metadata:
  name: anuja-app-deployment
spec: #define deployment
  replicas: 3 #number of pods
  selector:
    matchLabels:
      app: anujalabel 
  template:
    metadata:
      labels:
        app: anujalabel 
    spec: #define pod behaviour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
--- 
# writing service.yaml file to expose the application
apiVersion: v1
kind: Service
metadata:
  name: anuja-app-svc
spec:
  selector:
    app: anujalabel 
  ports:
  - port: 3016 #service port number
    targetPort: 3015 #container port number
  type: LoadBalancer #type of service

